import test from 'node:test';import assert from 'node:assert/strict';
import {createDemo} from '../src/demo';import {execute,stateForUser,validateState,type State} from '../src/domain';
import {stockRows} from '../src/inventory';import {buildProductionPlan} from '../src/production';import {readBackup,makeBackup} from '../src/imports';
const now='2026-10-09T08:00:00.000Z';const cmd=(s:State,c:unknown,u='demo-admin')=>execute(s,u,c,now);
const row=(s:State)=>stockRows(s).find(p=>p.id==='demo-p1')!;
function counted(n:number,s=createDemo()){s=cmd(s,{type:'stock.count',items:[{productId:'demo-p1',countedQuantity:n,expectedOnHand:row(s).onHand}],reason:'İlk sayım'},'demo-shipping');return cmd(s,{type:'stock.review',id:s.inventory!.adjustments.at(-1)!.id,approve:true});}
function waiting(s:State,n:number){s=cmd(s,{type:'order.create',customerId:'demo-c1',items:[{id:'demo-p1',quantity:n}],discount:{type:'percent',value:0},vatMode:'product'},'demo-sales');return cmd(s,{type:'order.customerApprove',id:s.orders[0].id},'demo-sales');}
const approve=(s:State)=>cmd(s,{type:'order.approve',id:s.orders[0].id,deliveryDate:'2026-10-12',acceptPlanRisk:true});
test('count does not update stock before manager approval; zero is explicit',()=>{let s=counted(10);s=cmd(s,{type:'stock.count',items:[{productId:'demo-p1',countedQuantity:0,expectedOnHand:10}],reason:'Sayım'},'demo-shipping');assert.equal(row(s).onHand,10);s=cmd(s,{type:'stock.review',id:s.inventory!.adjustments.at(-1)!.id,approve:true});assert.equal(row(s).onHand,0);});
test('depot cannot approve its own count, sales cannot count or receive',()=>{let s=cmd(createDemo(),{type:'stock.count',items:[{productId:'demo-p1',countedQuantity:10,expectedOnHand:0}],reason:'Sayım'},'demo-shipping');assert.throws(()=>cmd(s,{type:'stock.review',id:s.inventory!.adjustments[0].id,approve:true},'demo-shipping'),/yetkiniz/);assert.throws(()=>cmd(s,{type:'stock.count',items:[{productId:'demo-p2',countedQuantity:1,expectedOnHand:0}],reason:'Sayım'},'demo-sales'),/yetkiniz/);});
test('reservation only follows approval and production uses shortage only',()=>{let s=waiting(counted(100),150);assert.equal(row(s).reserved,0);const preview=buildProductionPlan(s,'2026-10-09',{...s.orders[0],deliveryDate:'2026-10-12'});assert.equal(preview.allocations.reduce((n,a)=>n+a.quantity,0),50);assert.equal(row(s).reserved,0);s=approve(s);assert.equal(row(s).reserved,100);assert.equal(row(s).available,0);assert.equal(s.orders[0].items[0].pendingQuantity,50);});
test('two orders cannot reserve the same stock',()=>{let s=approve(waiting(counted(100),80));s=approve(waiting(s,50));assert.equal(row(s).reserved,100);assert.equal(s.orders[0].items[0].readyForShipmentQuantity,20);assert.equal(s.orders[0].items[0].pendingQuantity,30);});
test('production requires depot count before shipping, partial receipt supported',()=>{let s=approve(waiting(createDemo(),10)),id=s.orders[0].id;s=cmd(s,{type:'order.ready',id,items:[{id:'demo-p1',quantity:10}]},'demo-production');assert.equal(row(s).onHand,0);assert.equal(row(s).awaiting,10);assert.throws(()=>cmd(s,{type:'order.ship',id,items:[{id:'demo-p1',quantity:1}]},'demo-shipping'));s=cmd(s,{type:'order.receive',id,items:[{id:'demo-p1',quantity:4}]},'demo-shipping');assert.equal(row(s).onHand,4);assert.equal(row(s).reserved,4);assert.equal(row(s).awaiting,6);s=cmd(s,{type:'order.ship',id,items:[{id:'demo-p1',quantity:3}]},'demo-shipping');assert.equal(row(s).onHand,1);assert.equal(row(s).reserved,1);assert.equal(s.orders[0].items[0].sentQuantity,3);validateState(s);});
test('stock production is counted partially and cannot be received twice',()=>{let s=cmd(createDemo(),{type:'stock.produce',productId:'demo-p1',quantity:20},'demo-production'),id=s.inventory!.batches[0].id;s=cmd(s,{type:'stock.receive',id,quantity:8},'demo-shipping');assert.equal(row(s).available,8);s=cmd(s,{type:'stock.receive',id,quantity:12},'demo-shipping');assert.equal(row(s).available,20);assert.throws(()=>cmd(s,{type:'stock.receive',id,quantity:1},'demo-shipping'));assert.equal(buildProductionPlan(s,'2026-10-09').allocations[0].quantity,20);});
test('stale count cannot override movements after counting',()=>{let s=counted(10);s=cmd(s,{type:'stock.count',items:[{productId:'demo-p1',countedQuantity:9,expectedOnHand:10}],reason:'Sayım'},'demo-shipping');const id=s.inventory!.adjustments.at(-1)!.id;s=approve(waiting(s,2));s=cmd(s,{type:'order.ship',id:s.orders[0].id,items:[{id:'demo-p1',quantity:2}]},'demo-shipping');assert.throws(()=>cmd(s,{type:'stock.review',id,approve:true}),/stok değişti/);assert.equal(row(s).onHand,8);});
test('count cannot erase reserved stock; manager can release reservation with reason',()=>{let s=approve(waiting(counted(10),8));s=cmd(s,{type:'stock.count',items:[{productId:'demo-p1',countedQuantity:5,expectedOnHand:10}],reason:'Hasarlı'},'demo-shipping');const id=s.inventory!.adjustments.at(-1)!.id;assert.throws(()=>cmd(s,{type:'stock.review',id,approve:true}),/ayrılan/);s=cmd(s,{type:'order.release',id:s.orders[0].id,items:[{id:'demo-p1',quantity:3}],reason:'Sayım farkı'});s=cmd(s,{type:'stock.review',id,approve:true});assert.equal(row(s).onHand,5);assert.equal(row(s).reserved,5);assert.equal(s.orders[0].items[0].pendingQuantity,3);});
test('cancellation releases allocation without losing physical inventory',()=>{let s=approve(waiting(counted(10),8));s=cmd(s,{type:'order.cancel',id:s.orders[0].id,reason:'Müşteri vazgeçti'});assert.equal(row(s).onHand,10);assert.equal(row(s).available,10);});
test('bulk count validates atomically and rejects duplicates and fractions',()=>{const s=createDemo();for(const items of [[{productId:'demo-p1',countedQuantity:1.5,expectedOnHand:0}],[{productId:'demo-p1',countedQuantity:1,expectedOnHand:0},{productId:'demo-p1',countedQuantity:2,expectedOnHand:0}],[{productId:'demo-p1',countedQuantity:1,expectedOnHand:0},{productId:'missing',countedQuantity:2,expectedOnHand:0}]])assert.throws(()=>cmd(s,{type:'stock.count',items,reason:'Sayım'}));assert.equal(s.inventory!.adjustments.length,0);});
test('rejected count has no stock movement and permits recount',()=>{let s=cmd(createDemo(),{type:'stock.count',items:[{productId:'demo-p1',countedQuantity:10,expectedOnHand:0}],reason:'Sayım'});s=cmd(s,{type:'stock.review',id:s.inventory!.adjustments[0].id,approve:false});assert.equal(row(s).onHand,0);s=counted(12,s);assert.equal(row(s).onHand,12);});
test('sales stock totals include others reservations without exposing their records',()=>{let s=approve(waiting(counted(100),30));s.users.push({...s.users[1],id:'other',email:'other@example.test'});const v=stateForUser(s,s.users.at(-1)!);assert.equal(v.orders.length,0);assert.equal(v.inventory,undefined);assert.equal(v.stockSummary?.find(p=>p.id==='demo-p1')?.available,70);const depot=stateForUser(s,s.users[3]);assert.equal(depot.products.length,0);assert.equal(depot.orders[0].items[0].price,0);});
test('legacy ready quantities migrate to depot acceptance, without fabricated stock',()=>{const s=approve(waiting(createDemo(),5));delete s.inventory;s.orders[0].items[0].pendingQuantity=0;s.orders[0].items[0].readyForShipmentQuantity=5;s.orders[0].status='Sevkiyata Hazır';const migrated=validateState(s);assert.equal(row(migrated).onHand,0);assert.equal(row(migrated).awaiting,5);assert.equal(migrated.orders[0].items[0].readyForShipmentQuantity,0);});
test('backup preserves stock movements, count decisions and reservations',()=>{const s=approve(waiting(counted(100),30));assert.deepEqual(readBackup(JSON.stringify(makeBackup(s))),s);const target=createDemo();target.products=[];target.customers=[];const restored=cmd(target,{type:'backup.import',data:s,ownerId:'demo-admin'});assert.equal(row(restored).onHand,100);assert.equal(row(restored).reserved,30);});
