import test from 'node:test';
import assert from 'node:assert/strict';
import {createDemo} from '../src/demo';
import {execute,emptyState,stateForUser,validateState,totals,searchMatch,type State} from '../src/domain';
import {parseProducts,makeBackup,readBackup,readLegacy,readImport} from '../src/imports';
import {authorizeIdentity} from '../server/identity';
import {printHtml,ordersCSV,dateKey} from '../src/outputs';
const admin='demo-admin',sales='demo-sales',production='demo-production',shipping='demo-shipping';
function created(){return execute(createDemo(),sales,{type:'order.create',customerId:'demo-c1',items:[{id:'demo-p1',quantity:2}],discount:{type:'percent',value:10},vatMode:'product'});}
function approved(){let s=created();s=execute(s,sales,{type:'order.customerApprove',id:s.orders[0].id});return execute(s,admin,{type:'order.approve',id:s.orders[0].id});}
function ready(){const s=approved();return execute(s,production,{type:'order.ready',id:s.orders[0].id,items:[{id:'demo-p1',quantity:2}]});}
test('partial shipping stays open and the final shipment closes it',()=>{
 let s=ready();s=execute(s,shipping,{type:'order.ship',id:s.orders[0].id,items:[{id:'demo-p1',quantity:1}]});
 assert.equal(s.orders[0].status,'Sevkiyata Hazır');assert.equal(s.orders[0].items[0].readyForShipmentQuantity,1);
 s=execute(s,shipping,{type:'order.ship',id:s.orders[0].id,items:[{id:'demo-p1',quantity:1}]});
 assert.equal(s.orders[0].status,'Tamamlandı');assert.equal(s.orders[0].shipments.length,2);assert.equal(s.audit.length,6);validateState(s);
});
for(const quantity of [0,-1,0.5,3,Infinity,NaN])test(`reject invalid shipment quantity ${quantity} without changing source`,()=>{const s=ready(),before=JSON.stringify(s);assert.throws(()=>execute(s,shipping,{type:'order.ship',id:s.orders[0].id,items:[{id:'demo-p1',quantity}]}));assert.equal(JSON.stringify(s),before);});
test('production cannot start before both approvals',()=>{const s=created();assert.throws(()=>execute(s,production,{type:'order.ready',id:s.orders[0].id,items:[{id:'demo-p1',quantity:1}]}));});
test('sales cannot forge manager approval',()=>{let s=created();s=execute(s,sales,{type:'order.customerApprove',id:s.orders[0].id});assert.throws(()=>execute(s,sales,{type:'order.approve',id:s.orders[0].id}),/yetkiniz/);});
test('different salesperson cannot approve or view another order',()=>{const s=created();s.users.push({...s.users[1],id:'other',email:'other@example.test'});assert.throws(()=>execute(s,'other',{type:'order.customerApprove',id:s.orders[0].id}),/kendi/);assert.equal(stateForUser(s,s.users[4]).orders.length,0);});
test('inactive user cannot act',()=>{const s=created();s.users[0].active=false;assert.throws(()=>execute(s,admin,{type:'product.archive',id:'demo-p1'}),/pasif/);});
test('cannot cancel a partially shipped order',()=>{let s=ready();s=execute(s,shipping,{type:'order.ship',id:s.orders[0].id,items:[{id:'demo-p1',quantity:1}]});assert.throws(()=>execute(s,admin,{type:'order.cancel',id:s.orders[0].id,reason:'Test'}),/Gönderilmiş/);});
test('reopening requires new approvals and resets production quantities',()=>{let s=ready();s=execute(s,admin,{type:'order.cancel',id:s.orders[0].id,reason:'Müşteri değişikliği'});s=execute(s,admin,{type:'order.reopen',id:s.orders[0].id});assert.equal(s.orders[0].status,'Müşteriden Onay Bekleniyor');assert.equal(s.orders[0].managerApprovedAt,undefined);assert.equal(s.orders[0].items[0].pendingQuantity,2);assert.equal(s.orders[0].items[0].readyForShipmentQuantity,0);});
test('editing stock code preserves identity and historical price',()=>{const before=created();const s=execute(before,admin,{type:'product.save',product:{...before.products[0],code:'YENI22',price:2000}});assert.equal(s.products.length,3);assert.equal(s.products[0].id,'demo-p1');assert.equal(s.orders[0].items[0].price,1360);assert.equal(s.orders[0].items[0].code,'SCC22');});
test('duplicate normalized codes rejected',()=>{const s=createDemo();assert.throws(()=>execute(s,admin,{type:'product.save',product:{...s.products[1],code:'scc22'}}),/stok kodu/);});
test('archived product cannot be ordered',()=>{const s=execute(createDemo(),admin,{type:'product.archive',id:'demo-p1'});assert.throws(()=>execute(s,sales,{type:'order.create',customerId:'demo-c1',items:[{id:'demo-p1',quantity:1}],discount:{type:'percent',value:0},vatMode:'none'}),/aktif/);});
test('new customer is persisted with the order',()=>{const s=execute(createDemo(),sales,{type:'order.create',customer:{name:'Yeni müşteri',company:'',phone:'',address:'',note:'',active:true},items:[{id:'demo-p1',quantity:1}],discount:{type:'percent',value:0},vatMode:'none'});assert.equal(s.customers.length,2);assert.equal(s.customers[1].id,s.orders[0].customer.id);});
test('UUID order IDs do not collide within a single timestamp',()=>{const s=created(),input={type:'order.create',customerId:'demo-c1',items:[{id:'demo-p1',quantity:1}],discount:{type:'percent',value:0},vatMode:'none'};const a=execute(s,sales,input),b=execute(s,sales,input);assert.notEqual(a.orders[0].number,b.orders[0].number);});
test('discount and VAT calculated in cents per product',()=>{const order=created().orders[0];assert.equal(totals(order).total,2937.6);order.items=[{...order.items[0],price:100,quantity:1,kdvRate:20},{...order.items[0],id:'second',price:100,quantity:1,kdvRate:10}];order.discount={type:'amount',value:20};assert.deepEqual(totals(order).lines.map(l=>l.vat),[18,9]);assert.equal(totals(order).total,207);});
test('one-cent discount allocation has no rounding loss',()=>{const order=created().orders[0];order.items=[1,2,3].map(n=>({...order.items[0],id:String(n),price:1,quantity:1,kdvRate:0}));order.discount={type:'amount',value:0.01};assert.equal(totals(order).lines.reduce((n,l)=>n+l.discount,0),0.01);assert.equal(totals(order).total,2.99);});
test('over-limit fixed discount and fractional order quantity rejected',()=>{const input={type:'order.create',customerId:'demo-c1',items:[{id:'demo-p1',quantity:1}],discount:{type:'amount',value:9999},vatMode:'none'};assert.throws(()=>execute(createDemo(),sales,input),/aşamaz/);assert.throws(()=>execute(createDemo(),sales,{...input,items:[{id:'demo-p1',quantity:0.5}]}));});
test('production response does not leak prices, catalog or other accounts',()=>{const s=approved(),view=stateForUser(s,s.users[2]);assert.equal(view.products.length,0);assert.equal(view.customers.length,0);assert.equal(view.users.length,1);assert.equal(view.orders[0].items[0].price,0);assert.equal(view.orders[0].discount.value,0);});
test('self-removal of admin access rejected',()=>{const s=createDemo();assert.throws(()=>execute(s,admin,{type:'user.save',user:{...s.users[0],role:'uretim'}}),/Kendi/);});
test('Turkish search matches partial stock code and product words',()=>{assert.ok(searchMatch('çıkış alümin','Çift Çıkışlı Alüminyum Merdiven'));assert.ok(searchMatch('cc2','SCC22'));});
test('CSV parses Turkish decimal and preserves zero VAT',()=>{const p=parseProducts('Sıra;Stok kodu;Ürün;Fiyat;KDV\n1;ABC;Merdiven;1.234,56;0');assert.equal(p[0].price,1234.56);assert.equal(p[0].kdvRate,0);});
test('CSV duplicates and malformed rows rejected',()=>{assert.throws(()=>parseProducts('1;A;Ürün;1;20\n2;a;Ürün;2;20'),/yinelenen/);assert.throws(()=>parseProducts('1;A;Ürün;1;20;extra'),/5 sütun/);});
test('backup round trip and invalid version rejection',()=>{const s=ready();assert.deepEqual(readBackup(JSON.stringify(makeBackup(s))),s);assert.throws(()=>readBackup(JSON.stringify({...makeBackup(s),version:3})),/desteklenen/);assert.throws(()=>readBackup('{broken'));});
test('backup rejects conflicting shipment history',()=>{const s=ready();s.orders[0].items[0].sentQuantity=1;s.orders[0].items[0].readyForShipmentQuantity=1;assert.throws(()=>validateState(s),/geçmişi/);});
test('backup cannot grant imported user access or overwrite existing records',()=>{const target=emptyState();target.users=[createDemo().users[0]];const source=created();const s=execute(target,admin,{type:'backup.import',ownerId:admin,data:source});assert.equal(s.users.length,1);assert.equal(s.orders[0].createdByUserId,admin);assert.equal(s.audit.length,1);assert.throws(()=>execute(s,admin,{type:'backup.import',ownerId:admin,data:source}),/boş sisteme/);});
test('only verified exact bootstrap email creates first administrator',()=>{const s=emptyState();assert.throws(()=>authorizeIdentity(s,{email:'admin@example.test',emailConfirmed:false},'admin@example.test'));assert.throws(()=>authorizeIdentity(s,{email:'other@example.test',emailConfirmed:true},'admin@example.test'));assert.equal(s.users.length,0);assert.equal(authorizeIdentity(s,{email:'ADMIN@example.test',emailConfirmed:true},'admin@example.test').role,'admin');assert.equal(s.revision,1);});
test('bootstrap cannot recreate access after user disabled',()=>{const s=createDemo();s.users[0].active=false;assert.throws(()=>authorizeIdentity(s,{email:s.users[0].email,emailConfirmed:true},s.users[0].email));});
test('print escapes customer markup and contains discount total',()=>{const o=created().orders[0];o.customer.name='<script>alert(1)</script>';const html=printHtml(o);assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('İskonto sonrası'));assert.ok(html.includes('2.937,60'));});
test('CSV neutralizes formula payloads',()=>{const s=created();s.orders[0].customer.name='=HYPERLINK("evil")';assert.ok(ordersCSV(s.orders).includes("\"'=HYPERLINK"));});
test('date filtering uses Istanbul calendar day across UTC midnight',()=>{assert.equal(dateKey('2026-10-06T22:30:00Z'),'2026-10-07');});
test('CSV neutralizes a formula behind leading whitespace',()=>{const s=created();s.orders[0].customer.name='  =1+1';assert.ok(ordersCSV(s.orders).includes("\"'  =1+1\""));});
test('legacy file can be imported on a different origin without passwords',()=>{const p=createDemo().products[0];const r=readImport(JSON.stringify({format:'siparis-legacy',version:20,data:{products:[p],customers:[],orders:[],users:[{password:'must-not-import'}]}}));assert.equal(r.data.products.length,1);assert.equal(r.data.users.length,0);assert.ok(!JSON.stringify(r.data).includes('must-not-import'));});
test('capacity failure leaves source state unchanged',()=>{const s=createDemo();s.audit=Array.from({length:1200},(_,n)=>({id:String(n),at:'2026-10-07T08:00:00Z',actorId:admin,actorName:'Yönetici',action:'test',targetId:'test',detail:'a'.repeat(1800)}));const before=JSON.stringify(s);assert.throws(()=>execute(s,admin,{type:'product.archive',id:'demo-p1'}),/kapasite/);assert.equal(JSON.stringify(s),before);});
test('excessive monetary total is rejected before saving',()=>{const s=createDemo();s.products[0].price=100000000;assert.throws(()=>execute(s,sales,{type:'order.create',customerId:'demo-c1',items:[{id:'demo-p1',quantity:1000000}],discount:{type:'percent',value:0},vatMode:'none'}),/sınırını/);assert.equal(s.orders.length,0);});
test('legacy migration corrects status and quantities without reading old passwords',()=>{
 const p={id:1,orderNo:1,code:'ABC',name:'Ürün',price:100,kdvRate:20};
 const values:Record<string,unknown>={siparis_products_v20:[p],siparis_orders_v20:[{id:'SIP-1',createdAt:'06.10.2026 12:00:00',createdBy:'Eski',customer:{id:1,name:'Müşteri'},items:[{...p,quantity:2,pendingQuantity:0,readyForShipmentQuantity:1,sentQuantity:0}],status:'Tamamlandı',vatRate:20,shipments:[]}]};
 const storage={getItem:(key:string)=>{assert.ok(!key.includes('users'));return key in values?JSON.stringify(values[key]):null;}};
 const result=readLegacy(storage);assert.equal(result.data.orders[0].status,'Sevkiyata Hazır');assert.equal(result.data.orders[0].items[0].pendingQuantity,1);assert.equal(result.data.users.length,0);assert.equal(result.warnings.length,3);
});
