import {useState} from 'react';
import {Download,Upload} from 'lucide-react';
import {type State} from './domain';
import {makeBackup,readImport,readLegacy} from './imports';
import {download,date} from './outputs';
import {useStore,message} from './store';
import {Field,Section,Empty} from './ui';
export function Backups(){
 const {state,user,run,busy,setError,setNotice}=useStore();const [preview,setPreview]=useState<State|null>(null),[warnings,setWarnings]=useState<string[]>([]),[owner,setOwner]=useState(user!.id),[consent,setConsent]=useState(false);
 const clear=()=>{setPreview(null);setWarnings([]);setConsent(false);};
 const isEmpty=!state!.orders.length&&!state!.products.length&&!state!.customers.length;
 return <Section title="Yedekleme ve aktarım" description="Verilerinizi dosyaya indirin. Aktarımdan önce içeriği kontrol edin."><div className="surface"><h2>Yedek al</h2><p>{state!.orders.length} sipariş, {state!.products.length} ürün, {state!.customers.length} müşteri ve işlem geçmişi.</p><button className="primary" onClick={()=>{download('siparis-yedek-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(makeBackup(state!)));setNotice('Yedek dosyası hazırlandı. Dosyayı güvenli arşivinizde saklayın.');}}><Download size={16}/>Yedeği indir</button><p className="muted small">Dosya müşteri ve iletişim bilgileri içerir. Hesap parolaları yedekte bulunmaz.</p></div><div className="surface"><h2>Yedekten aktar</h2><p>Aktarım boş bir çalışma alanına yapılır. Eski kullanıcıların yetkileri aktarılmaz. Siparişler aşağıda seçtiğiniz kullanıcıya bağlanır.</p>{!isEmpty&&<div className="alert">Mevcut çalışma alanında kayıt var. Yedeği kontrol edebilirsiniz; üzerine yazma engellendi.</div>}<Field label="Yedek dosyası (.json)"><input type="file" accept=".json,application/json" onChange={async e=>{clear();const file=e.target.files?.[0];if(!file)return;if(file.size>4000000)return setError('Dosya 4 MB sınırını aşıyor.');try{const imported=readImport(await file.text());setPreview(imported.data);setWarnings(imported.warnings);setError('');}catch(error){setError(message(error));}}}/></Field><button onClick={()=>{clear();try{const r=readLegacy(localStorage);setPreview(r.data);setWarnings(r.warnings);setError('');}catch(e){setError(message(e));}}}>Bu tarayıcıdaki eski sürüm kayıtlarını kontrol et</button>{preview&&<div className="import-preview"><h3>Aktarım önizlemesi</h3><p>{preview.orders.length} sipariş · {preview.products.length} ürün · {preview.customers.length} müşteri</p>{warnings.map((w,i)=><p key={i}>{w}</p>)}<button onClick={()=>download('eski-surum-donusturulmus-yedek.json',JSON.stringify(makeBackup(preview)))}><Download size={16}/>Önizlemenin yedeğini indir</button><Field label="Siparişlerin yeni sahibi"><select value={owner} onChange={e=>setOwner(e.target.value)}>{state!.users.filter(u=>u.active&&['admin','pazarlamaci'].includes(u.role)).map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></Field><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>İçeriği ve sipariş sahibini kontrol ettim.</label><button className="primary" disabled={busy||!consent||!isEmpty} onClick={async()=>{if(await run({type:'backup.import',data:preview,ownerId:owner}))clear();}}><Upload size={16}/>Aktarımı tamamla</button></div>}</div></Section>;
}
export function Audit(){const {state}=useStore();const [limit,setLimit]=useState(100);const labels:Record<string,string>={'order.create':'Sipariş oluşturuldu','order.customerApprove':'Müşteri onayı','order.approve':'Yönetici onayı','order.reschedule':'Teslim tarihi değişikliği','production.configure':'Üretim takvimi ayarı','order.ready':'Üretim kaydı','order.ship':'Sevkiyat kaydı','order.cancel':'Sipariş iptali','order.reopen':'Sipariş yeniden açıldı','product.save':'Ürün kaydı','product.archive':'Ürün arşivlendi','product.import':'Toplu ürün aktarımı','customer.save':'Müşteri kaydı','customer.archive':'Müşteri arşivlendi','user.save':'Kullanıcı erişimi','backup.import':'Yedek aktarıldı'};return <Section title="İşlem geçmişi" description="Kim, ne zaman, hangi işlemi yaptı?"><div className="surface table-scroll"><table><thead><tr><th>Tarih</th><th>Kullanıcı</th><th>İşlem</th><th>Açıklama</th></tr></thead><tbody>{state!.audit.slice().reverse().slice(0,limit).map(a=><tr key={a.id}><td>{date(a.at)}</td><td>{a.actorName}</td><td>{labels[a.action]??a.action}</td><td>{a.detail||'—'}</td></tr>)}</tbody></table>{!state!.audit.length&&<Empty>Henüz işlem yapılmadı.</Empty>}{state!.audit.length>limit&&<button onClick={()=>setLimit(limit+100)}>100 kayıt daha göster</button>}</div></Section>;}


