import {useEffect,useRef,useState} from 'react';
import {Building2} from 'lucide-react';
import {defaultCompany,rememberBrand,rememberedBrand,prepareCompanyImage,type Company} from './company';
import {useStore,message} from './store';
import {Field,Section} from './ui';
import {roleNames} from './domain';
export function CompanyLogo({company}:{company:Company}){return company.logo?<img className="company-logo" src={company.logo} alt={company.name+' logosu'}/>:<Building2 size={30} aria-hidden="true"/>;}
export function BrandingLifecycle(){const {state,user}=useStore();const company=state?.company;useEffect(()=>{const brand=state?(company??defaultCompany()):rememberedBrand();document.title=brand.name+' · Sipariş yönetimi';if(state)rememberBrand(brand);},[company,!!state,user?.id]);return null;}
export function LoginBrand(){const [company]=useState(rememberedBrand);return <div className="login-brand"><CompanyLogo company={company}/><span>{company.name}</span></div>;}
export function CompanyWelcome(){const {state,user}=useStore();const company=state?.company??defaultCompany();if(!user)return null;const descriptions={admin:'Siparişleri, ekibinizi ve üretim planını buradan yönetin.',pazarlamaci:'Kendi siparişlerinizi ve müşteriye verdiğiniz teklifleri takip edin.',uretim:'Günün üretim planını inceleyin ve hazırlanan miktarları kaydedin.',sevkiyat:'Üretimden sayarak teslim alın, stok sayımı yapın ve sevkiyatları kaydedin.'};return <div className="company-welcome">{company.photo&&<img className="company-photo" src={company.photo} alt={company.name+' şirket fotoğrafı'}/>}<div className="welcome-copy"><span className="company-eyebrow">{company.name} · {roleNames[user.role]}</span><h2>Hoş geldiniz, {user.name}</h2><p>{descriptions[user.role]}</p></div></div>;}
export function CompanySettings(){
 const {state,run,busy,setError}=useStore();const [form,setForm]=useState(()=>state?.company??defaultCompany()),[uploading,setUploading]=useState(false);const generation=useRef(0);
 useEffect(()=>()=>{generation.current++;},[]);
 const set=(key:keyof Company,value:string)=>setForm(prev=>({...prev,[key]:value}));
 const upload=async(file:File|undefined,kind:'logo'|'photo')=>{if(!file)return;const token=++generation.current;setUploading(true);try{const data=await prepareCompanyImage(file,kind);if(token===generation.current)set(kind,data);}catch(e){if(token===generation.current)setError(message(e));}finally{if(token===generation.current)setUploading(false);}};
 return <Section title="Şirket bilgileri" description="Şirketinizin tüm kullanıcılarda görünen kimliği. Bu alanı yalnızca yönetici düzenleyebilir."><form onSubmit={async e=>{e.preventDefault();await run({type:'company.save',company:form});}}><fieldset disabled={busy||uploading} className="company-fields"><div className="management-grid"><div className="surface"><h2>Logo ve şirket fotoğrafı</h2><p className="muted">PNG, JPEG veya WebP; en fazla 8 MB. Görseller otomatik küçültülür. Değişiklikler Kaydet ile uygulanır.</p>{(['logo','photo'] as const).map(kind=><div className="company-upload" key={kind}><Field label={kind==='logo'?'Şirket logosu yükle':'Şirket fotoğrafı yükle'}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void upload(e.target.files?.[0],kind);e.target.value='';}}/></Field>{form[kind]&&<><img className={kind==='logo'?'logo-preview':'photo-preview'} src={form[kind]} alt={kind==='logo'?'Logo önizlemesi':'Şirket fotoğrafı önizlemesi'}/><button type="button" onClick={()=>set(kind,'')}>{kind==='logo'?'Logoyu kaldır':'Fotoğrafı kaldır'}</button></>}</div>)}<div className="brand-preview"><CompanyLogo company={form}/><strong>{form.name||'Şirket adı'}</strong></div><p className="muted small">Logo menüde ve çıktılarda, fotoğraf sayfaların karşılama alanında görünür.</p></div><div className="surface"><h2>Şirket ve iletişim</h2><div className="form-grid">{([['name','Ekranda görünen şirket adı',120],['legalName','Ticari unvan',200],['phone','Şirket telefonu',50],['email','Şirket e-postası',254],['website','Web sitesi',200],['taxOffice','Vergi dairesi',100],['taxNumber','Vergi numarası',30]] as const).map(([key,label,max])=><Field key={key} label={label}><input required={key==='name'} maxLength={max} type={key==='email'?'email':key==='website'?'url':key==='phone'?'tel':'text'} value={form[key]} onChange={e=>set(key,e.target.value)}/></Field>)}</div><Field label="Şirket adresi"><textarea rows={3} maxLength={600} value={form.address} onChange={e=>set('address',e.target.value)}/></Field><p className="muted small">Ad soyad bilgileri Kullanıcılar ekranından düzenlenir. Her kişi kendi hesabındaki ad soyad ile karşılanır.</p></div></div><button className="primary" type="submit">{uploading?'Görsel hazırlanıyor…':'Şirket bilgilerini kaydet'}</button></fieldset></form></Section>;
}
