import {useState} from 'react';
import {PackageCheck,ArrowRight} from 'lucide-react';
import {auth,cloudConfigured,message,useStore} from './store';
import {Field} from './ui';
export function Login(){
 const {startDemo,error,setError,setNotice,notice}=useStore();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[signup,setSignup]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();if(!auth)return;setBusy(true);setError('');try{const result=signup?await auth.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}):await auth.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(signup)setNotice('E-posta kutunuzdaki doğrulama bağlantısını açın. Sisteme erişim için yöneticinin e-postanızı kullanıcı listesine eklemesi gerekir.');}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function reset(){if(!auth||!email)return setError('Önce e-posta adresinizi yazın.');setBusy(true);try{const r=await auth.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/?reset=1'});if(r.error)throw r.error;setNotice('Hesap varsa şifre yenileme bağlantısı e-posta adresinize gönderildi.');}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <main className="login-page"><div className="login-intro"><PackageCheck size={40}/><span className="eyebrow">MOBİL SİPARİŞ</span><h1>Siparişten<br/>teslimata.</h1><p>Satış, üretim ve sevkiyat ekibinizin<br/>ortak çalışma alanı.</p><div className="login-foot">Sipariş yönetimi · Sürüm 0.3.0</div></div><div className="login-panel"><h2>{signup?'Hesap oluştur':'Çalışma alanına giriş'}</h2><p className="muted">İş e-postanız ve şifrenizle devam edin.</p>{error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status">{notice}</div>}{cloudConfigured?<form onSubmit={submit}><Field label="E-posta"><input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></Field><Field label="Şifre"><input type="password" autoComplete={signup?'new-password':'current-password'} minLength={signup?12:undefined} value={password} onChange={e=>setPassword(e.target.value)} required/></Field><button className="primary wide" disabled={busy}>{busy?'Lütfen bekleyin…':signup?'Hesap oluştur':'Giriş yap'}<ArrowRight size={17}/></button><div className="actions"><button type="button" className="link" onClick={()=>setSignup(!signup)} disabled={busy}>{signup?'Giriş ekranına dön':'Yeni hesap'}</button><button type="button" className="link" onClick={reset} disabled={busy}>Şifremi unuttum</button></div></form>:<div className="alert">Ekip kullanımı için merkezi sistem kurulumu gerekiyor. Kurulum tamamlanınca güvenli giriş burada açılacak.</div>}<div className="demo-entry"><h3>Uygulamayı dene</h3><p>Örnek ürünlerle tüm rolleri inceleyin. Deneme kayıtları yalnızca bu tarayıcıda tutulur.</p><button onClick={startDemo}>Deneme alanını aç <ArrowRight size={16}/></button></div></div></main>;
}
export function PasswordReset(){const {setError}=useStore();const [password,setPassword]=useState(''),[busy,setBusy]=useState(false);return <form className="reset-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await auth!.auth.updateUser({password});if(result.error)throw result.error;history.replaceState(null,'',location.pathname);location.reload();}catch(e){setError(message(e));}finally{setBusy(false);}}}><h1>Yeni şifre belirle</h1><Field label="Yeni şifre (en az 12 karakter)"><input autoComplete="new-password" type="password" minLength={12} value={password} onChange={e=>setPassword(e.target.value)} required/></Field><button className="primary" disabled={busy}>Şifreyi güncelle</button></form>;}
