import {totals,type Order,type State} from './domain';
export const currency=(n:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(n);
export const date=(iso:string)=>new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Istanbul'}).format(new Date(iso));
export const dateKey=(iso:string)=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Europe/Istanbul'}).format(new Date(iso));
export const shortNumber=(n:string)=>n.startsWith('SIP-')&&n.length>30?n.slice(0,21).toUpperCase():n;
export const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function printHtml(order:Order,shipment?:Order['shipments'][number]){
 const t=totals(order),h=escapeHtml;
 const title=shipment?'Sevkiyat Fişi':['Müşteriden Onay Bekleniyor','Yönetici Onayı Bekleniyor'].includes(order.status)?'Teklif':'Sipariş';
 const rows=shipment?shipment.items.map(i=>`<tr><td>${h(i.code)}</td><td>${h(i.name)}</td><td>${i.quantity}</td></tr>`).join(''):order.items.map((i,n)=>`<tr><td>${h(i.code)}</td><td>${h(i.name)}</td><td>${i.quantity}</td><td>${h(currency(i.price))}</td><td>${h(currency(t.lines[n].discount))}</td><td>${order.vatMode==='product'?i.kdvRate:0}%</td><td>${h(currency(t.lines[n].total))}</td></tr>`).join('');
 return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>${h(title)} ${h(order.number)}</title><style>body{font-family:Arial,sans-serif;color:#152d35;margin:32px;font-size:13px}h1{font-size:26px}table{border-collapse:collapse;width:100%;margin-top:24px}th,td{border-bottom:1px solid #ccd5d9;padding:10px;text-align:left}th{background:#eef3f3}.totals{text-align:right;margin-top:24px}small{word-break:break-all}@media print{button{display:none}}</style></head><body><h1>${title}</h1><p><strong>${h(order.customer.company||order.customer.name)}</strong><br>${h(order.customer.name)}<br>${h(order.customer.address)}<br>${h(order.customer.phone)}</p><small>Sipariş no: ${h(order.number)}</small><p>${h(date(shipment?.createdAt??order.createdAt))}</p>${shipment?`<small>Sevkiyat no: ${h(shipment.id)}</small>`:''}<table><thead><tr><th>Kod</th><th>Ürün</th><th>Adet</th>${shipment?'':'<th>Birim fiyat</th><th>İskonto</th><th>KDV</th><th>Toplam</th>'}</tr></thead><tbody>${rows}</tbody></table>${shipment?'':`<div class="totals"><p>Liste toplamı: ${h(currency(t.base))}</p><p>İskonto: ${h(currency(t.discount))}${order.discount.type==='percent'?` (%${order.discount.value})`:''}</p><p>İskonto sonrası: ${h(currency(t.net))}</p><p>KDV: ${h(currency(t.vat))}</p><h2>Genel toplam: ${h(currency(t.total))}</h2></div>`}<p>Durum: ${h(order.status)}</p><p>Bu çıktı sipariş / sevkiyat kaydıdır.</p></body></html>`;
}
export function printOrder(order:Order,shipment?:Order['shipments'][number]){
 const win=window.open('','_blank');if(!win)throw new Error('Yazdırma penceresi engellendi. Bu site için açılır pencereye izin verin.');
 win.opener=null;win.document.write(printHtml(order,shipment));win.document.close();win.focus();win.print();
}
export function orderText(order:Order){const t=totals(order);return [`Sipariş ${order.number}`,order.customer.company,order.customer.name,...order.items.map(i=>`${i.code} - ${i.name}: ${i.quantity} adet × ${currency(i.price)}`),`Liste toplamı: ${currency(t.base)}`,`İskonto: ${currency(t.discount)}`,`İskonto sonrası: ${currency(t.net)}`,`KDV: ${currency(t.vat)}`,`Genel toplam: ${currency(t.total)}`].filter(Boolean).join('\n');}
export function download(name:string,content:string,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const csvCell=(v:unknown)=>{const value=String(v??'');return '"'+(/^[\s]*[=+@\-]|^[\t\r\n]/.test(value)?"'"+value:value).replaceAll('"','""')+'"';};
export function ordersCSV(orders:State['orders']){return '\uFEFF'+[['Sipariş no','Tarih','Müşteri','Firma','Durum','Genel toplam'],...orders.map(o=>[o.number,date(o.createdAt),o.customer.name,o.customer.company,o.status,totals(o).total.toFixed(2).replace('.',',')])].map(row=>row.map(csvCell).join(';')).join('\r\n');}
