import {useState} from 'react';
import {useStore} from './store';
import {stockRows} from './inventory';
import {searchMatch} from './domain';
import {Section,Field,Empty} from './ui';
import {date} from './outputs';
export function Warehouse(){
 const {state,user,run,busy}=useStore(),s=state!,rows=s.stockSummary??stockRows(s),depot=['admin','sevkiyat'].includes(user!.role),production=['admin','uretim'].includes(user!.role);
 const [query,setQuery]=useState(''),[productId,setProduct]=useState(''),[quantity,setQuantity]=useState(''),[received,setReceived]=useState<Record<string,string>>({});
 const shown=rows.filter(p=>searchMatch(query,p.code,p.name));
 return <Section title="Depo ve stok" description="Tek depo · Fiziksel stok, siparişlere ayrılan ve satılabilir miktarlar."><div className="alert">Üretimden çıkan ürün sayılarak teslim alınmadan stok artmaz. İlk depo stoğunu Stok Sayımı ekranında girip yöneticiye onaylatın. Eski sürümden gelen kabul bekleyen ürünleri önce teslim alın, ardından toplam fiziksel stoğu sayın.</div><Field label="Stokta ürün ara"><input value={query} onChange={e=>setQuery(e.target.value)}/></Field><div className="surface table-scroll"><table><thead><tr><th>Ürün</th><th>Depoda toplam</th><th>Siparişe ayrılan</th><th>Satılabilir</th><th>Depo kabulü bekleyen</th></tr></thead><tbody>{shown.slice(0,200).map(p=><tr key={p.id}><td><strong>{p.code}</strong><small>{p.name}{!p.active?' · Arşiv':''}</small></td><td>{p.onHand}</td><td>{p.reserved}</td><td><strong>{p.available}</strong></td><td>{p.awaiting}</td></tr>)}</tbody></table>{!shown.length&&<Empty>Ürün bulunamadı.</Empty>}{shown.length>200&&<p>İlk 200 ürün gösteriliyor; aramayla daraltın.</p>}</div>
 {production&&<form className="surface" onSubmit={async e=>{e.preventDefault();if(await run({type:'stock.produce',productId,quantity:Number(quantity)}))setQuantity('');}}><h2>Siparişten bağımsız stok üretimi</h2><p className="muted">Yalnızca tamamlanan üretimi kaydedin. Depocu sayarak teslim alacak. Siparişe bağlı üretimi Siparişler ekranından girin.</p><div className="form-grid"><Field label="Stok için üretilen ürün"><select required value={productId} onChange={e=>setProduct(e.target.value)}><option value="">Ürün seçin</option>{rows.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.code} · {p.name}</option>)}</select></Field><Field label="Stok için üretilen adet"><input required type="number" min="1" max="1000000" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></Field></div><button className="primary" disabled={busy}>Üretimi depoya bildir</button></form>}
 {(depot||production)&&<div className="surface"><h2>Stok üretiminden teslim alınacaklar</h2>{(s.inventory?.batches??[]).filter(b=>b.receivedQuantity<b.quantity).slice(0,100).map(b=><form className="warehouse-receipt" key={b.id} onSubmit={async e=>{e.preventDefault();if(await run({type:'stock.receive',id:b.id,quantity:Number(received[b.id])}))setReceived(prev=>({...prev,[b.id]:''}));}}><div><strong>{rows.find(p=>p.id===b.productId)?.code} · {b.quantity-b.receivedQuantity} adet bekliyor</strong><p>{date(b.createdAt)} · {b.createdBy}</p><small>Üretilen: {b.quantity} · Teslim alınan: {b.receivedQuantity}</small></div>{depot&&<><Field label="Sayarak teslim alınan adet"><input required type="number" min="1" max={b.quantity-b.receivedQuantity} step="1" value={received[b.id]??''} onChange={e=>setReceived({...received,[b.id]:e.target.value})}/></Field><button disabled={busy}>Depoya teslim al</button></>}</form>)}{!(s.inventory?.batches??[]).some(b=>b.receivedQuantity<b.quantity)&&<Empty>Bekleyen stok üretimi yok. Siparişe bağlı teslimleri Siparişler ekranından alın.</Empty>}</div>}
 {depot&&<div className="surface table-scroll"><h2>Son 100 stok hareketi</h2><table><thead><tr><th>Tarih</th><th>Ürün</th><th>Hareket</th><th>Adet</th><th>İşlemi yapan</th><th>Açıklama</th></tr></thead><tbody>{(s.inventory?.movements??[]).slice(-100).reverse().map(m=><tr key={m.id}><td>{date(m.at)}</td><td>{rows.find(p=>p.id===m.productId)?.code}</td><td>{{receipt:'Sipariş üretimi kabulü',stockReceipt:'Stok üretimi kabulü',shipment:'Sevkiyat çıkışı',adjustment:'Onaylı sayım farkı'}[m.kind]}</td><td>{m.quantity>0?'+':''}{m.quantity}</td><td>{m.actor}</td><td>{m.reason||'—'}</td></tr>)}</tbody></table></div>}
 </Section>;
}
export function StockCount(){
 const {state,user,run,busy}=useStore(),s=state!,rows=s.stockSummary??stockRows(s),admin=user!.role==='admin';
 const [query,setQuery]=useState(''),[draft,setDraft]=useState<Record<string,{value:string,expected:number}>>({}),[reason,setReason]=useState('');
 const pending=s.inventory?.adjustments.filter(a=>a.status==='pending')??[],entries=Object.entries(draft).filter(([,v])=>v.value!=='');
 return <Section title="Stok Sayımı" description="Raflardaki gerçek adedi sayın. Ayrılmış ürünler dahil depodaki toplam fiziksel miktarı girin."><div className="alert">Boş bırakılan ürün değişmez. 0 yazmak o üründen depoda hiç olmadığını belirtir. Sayımlar yönetici onayına gider; onaylanana kadar stok değişmez. İlk stok girişi de buradan yapılır.</div><form onSubmit={async e=>{e.preventDefault();if(await run({type:'stock.count',items:entries.map(([productId,v])=>({productId,countedQuantity:Number(v.value),expectedOnHand:v.expected})),reason})){setDraft({});setReason('');}}}><Field label="Sayımda ürün ara"><input value={query} onChange={e=>setQuery(e.target.value)}/></Field><div className="surface table-scroll"><table><thead><tr><th>Ürün</th><th>Kayıtlı stok</th><th>Ayrılmış</th><th>Sayılan gerçek adet</th><th>Fark</th></tr></thead><tbody>{rows.filter(p=>searchMatch(query,p.code,p.name)).slice(0,200).map(p=>{const d=draft[p.id],awaits=pending.some(a=>a.productId===p.id);return <tr key={p.id}><td><strong>{p.code}</strong><small>{p.name}</small>{awaits&&<small>Yönetici onayı bekleniyor</small>}</td><td>{p.onHand}{d&&d.expected!==p.onHand&&<small className="plan-warning">Stok değişti; sayımı yenileyin.</small>}</td><td>{p.reserved}</td><td><input className="quantity" aria-label={p.code+' sayılan adet'} type="number" min="0" max="1000000" step="1" disabled={busy||awaits} value={d?.value??''} onChange={e=>setDraft(prev=>({...prev,[p.id]:{value:e.target.value,expected:p.onHand}}))}/></td><td>{d&&d.value!==''?Number(d.value)-d.expected:'—'}</td></tr>;})}</tbody></table><p className="muted small">En fazla 200 ürün gösterilir. Arama değişse de girdiğiniz sayımlar korunur. Gönderimde en fazla 500 ürün kabul edilir.</p></div><Field label="Sayım açıklaması"><input required maxLength={200} value={reason} onChange={e=>setReason(e.target.value)} placeholder="İlk depo sayımı / dönem sonu sayımı / hasarlı ürün…"/></Field><button className="primary" disabled={busy||!entries.length||entries.length>500}>{entries.length} ürünün sayımını onaya gönder</button></form>
 <div className="surface table-scroll"><h2>Yönetici onayı bekleyen sayımlar</h2><table><thead><tr><th>Ürün</th><th>Önce</th><th>Sayılan</th><th>Fark</th><th>Sayım bilgisi</th>{admin&&<th>Karar</th>}</tr></thead><tbody>{pending.slice(0,200).map(a=><tr key={a.id}><td>{rows.find(p=>p.id===a.productId)?.code}</td><td>{a.expectedOnHand}</td><td>{a.countedQuantity}</td><td>{a.countedQuantity-a.expectedOnHand}</td><td>{a.requestedBy}<small>{date(a.createdAt)} · {a.reason}</small></td>{admin&&<td><div className="actions"><button disabled={busy} onClick={()=>run({type:'stock.review',id:a.id,approve:true})}>Sayımı onayla</button><button disabled={busy} onClick={()=>run({type:'stock.review',id:a.id,approve:false})}>Reddet</button></div></td>}</tr>)}</tbody></table>{!pending.length&&<Empty>Onay bekleyen sayım yok.</Empty>}</div>
 <div className="surface"><h2>Son 50 sayım sonucu</h2>{(s.inventory?.adjustments??[]).filter(a=>a.status!=='pending').slice(-50).reverse().map(a=><p key={a.id}><strong>{rows.find(p=>p.id===a.productId)?.code}</strong> · {a.expectedOnHand} → {a.countedQuantity} · {a.status==='approved'?'Onaylandı':'Reddedildi'} · {a.reviewedBy}<small className="muted"> · {a.reason}</small></p>)}</div></Section>;
}
